---
title: "STA304 - Surveys, Sampling and Observational Data"
author: "Neil Montgomery"
date: "2016-01-11"
output: ioslides_presentation
---
# preliminaries

## administrative details
|
--|--
date format | ISO8601
instructor | Neil Montgomery
email | neilm@mie.utoronto.ca
office | BA8132
website | portal (announcements, grades, etc.)
github | https://github.com/sta304 (lecture material, code, etc.)
office hours | any time (except T3-4 and F3-5)

## grading

what | when | weight
--|--|--|--
midterm 1 | 2016-02-11 | 25%
midterm 2 | 2016-03-24 | 25%
exam | TBA | 50%

## book

Official book: Scheaffer, R.L., III, W.M., Ott, D.R.L., Gerow, K.G., 2011. *Elementary Survey Sampling*, 7 edition. ed. Duxbury Press, Boston, MA.

A less elementary (modern) source available online: Thompson, S.K., 2012. *Sampling*, 3 edition. ed. Wiley, Hoboken, N.J.

The Classic: *Sampling Techniques* by Cochrane.

## who am I? who are you?

I'm a statistician who works in a research group in the Dept. of Industrial Engineering.

You have taken at least one university course in statistics. Maybe more than one.


